namespace NodeJS {
  export interface ProcessEnv {
    AUTH_RESEND_KEY,
    EMAIL_FROM,
    NEXT_PUBLIC_AUTH_RESEND_KEY,
    NEXT_PUBLIC_EMAIL_FROM,

    AUTH_LINKEDIN_ID,
    AUTH_LINKEDIN_SECRET,

    AUTH_GITHUB_ID,
    AUTH_GITHUB_SECRET,

    AUTH_GOOGLE_ID,
    AUTH_GOOGLE_SECRET,
  }
}